# Generated by Django 4.2.23 on 2026-05-19 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi_app', '0007_support_promocode_and_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='declined_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='remainder_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Не потрібно'), ('pending', 'Очікує оплати'), ('pending_deposit', 'Очікує передплати'), ('deposit_paid', 'Передплачено (100 грн)'), ('pending_remainder', 'Очікує доплати'), ('paid', 'Повністю оплачено'), ('failed', 'Помилка оплати')], default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('searching', 'Пошук водія'), ('accepted', 'Прийнято водієм'), ('waiting', 'Очікування пасажира'), ('in_progress', 'У дорозі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='new', max_length=20),
        ),
    ]
